package com.maxidev.repostars.ui.search

import androidx.compose.ui.graphics.Color

data class LanguageColor(
    val name: String,
    val color: Color
)

val languageColors = listOf(
    LanguageColor("ABAP", Color(0xFFE8274B)),
    LanguageColor("ActionScript", Color(0xFF882B0F)),
    LanguageColor("Ada", Color(0xFF02F88C)),
    LanguageColor("Agda", Color(0xFF315665)),
    LanguageColor("AGS Script", Color(0xFFB9D9FF)),
    LanguageColor("Alloy", Color(0xFF64C800)),
    LanguageColor("AMPL", Color(0xFFE6EFBB)),
    LanguageColor("ANTLR", Color(0xFF9DC3FF)),
    LanguageColor("API Blueprint", Color(0xFF2ACCA8)),
    LanguageColor("APL", Color(0xFF5A8164)),
    LanguageColor("Arc", Color(0xFFAA2AFE)),
    LanguageColor("Arduino", Color(0xFFBD79D1)),
    LanguageColor("ASP", Color(0xFF6A40FD)),
    LanguageColor("AspectJ", Color(0xFFA957B0)),
    LanguageColor("Assembly", Color(0xFF6E4C13)),
    LanguageColor("ATS", Color(0xFF1AC620)),
    LanguageColor("AutoHotkey", Color(0xFF6594B9)),
    LanguageColor("AutoIt", Color(0xFF1C3552)),
    LanguageColor("BlitzMax", Color(0xFFCD6400)),
    LanguageColor("Boo", Color(0xFFD4BEC1)),
    LanguageColor("Brainfuck", Color(0xFF2F2530)),
    LanguageColor("C Sharp", Color(0xFF178600)),
    LanguageColor("C", Color(0xFF555555)),
    LanguageColor("Chapel", Color(0xFF8DC63F)),
    LanguageColor("Cirru", Color(0xFFCCCCFF)),
    LanguageColor("Clarion", Color(0xFFDB901E)),
    LanguageColor("Clean", Color(0xFF3F85AF)),
    LanguageColor("Click", Color(0xFFE4E6F3)),
    LanguageColor("Clojure", Color(0xFFDB5855)),
    LanguageColor("CoffeeScript", Color(0xFF244776)),
    LanguageColor("ColdFusion CFC", Color(0xFFED2CD6)),
    LanguageColor("ColdFusion", Color(0xFFED2CD6)),
    LanguageColor("Common Lisp", Color(0xFF3FB68B)),
    LanguageColor("Component Pascal", Color(0xFFB0CE4E)),
    LanguageColor("cpp", Color(0xFFF34B7D)),
    LanguageColor("Crystal", Color(0xFF776791)),
    LanguageColor("CSS", Color(0xFF563D7C)),
    LanguageColor("D", Color(0xFFBA595E)),
    LanguageColor("Dart", Color(0xFF00B4AB)),
    LanguageColor("Diff", Color(0xFF88DDDD)),
    LanguageColor("DM", Color(0xFF447265)),
    LanguageColor("Dogescript", Color(0xFFCCA760)),
    LanguageColor("Dylan", Color(0xFF6C616E)),
    LanguageColor("E", Color(0xFFCCCE35)),
    LanguageColor("Eagle", Color(0xFF814C05)),
    LanguageColor("eC", Color(0xFF913960)),
    LanguageColor("ECL", Color(0xFF8A1267)),
    LanguageColor("edn", Color(0xFFDB5855)),
    LanguageColor("Eiffel", Color(0xFF946D57)),
    LanguageColor("Elixir", Color(0xFF6E4A7E)),
    LanguageColor("Elm", Color(0xFF60B5CC)),
    LanguageColor("Emacs Lisp", Color(0xFFC065DB)),
    LanguageColor("EmberScript", Color(0xFFFFF4F3)),
    LanguageColor("Erlang", Color(0xFFB83998)),
    LanguageColor("F#", Color(0xFFB845FC)),
    LanguageColor("Factor", Color(0xFF636746)),
    LanguageColor("Fancy", Color(0xFF7B9DB4)),
    LanguageColor("Fantom", Color(0xFFDBDED5)),
    LanguageColor("FLUX", Color(0xFF88CCFF)),
    LanguageColor("Forth", Color(0xFF341708)),
    LanguageColor("FORTRAN", Color(0xFF4D41B1)),
    LanguageColor("FreeMarker", Color(0xFF0050B2)),
    LanguageColor("Frege", Color(0xFF00CAFE)),
    LanguageColor("Game Maker Language", Color(0xFF8FB200)),
    LanguageColor("Glyph", Color(0xFFE4CC98)),
    LanguageColor("Gnuplot", Color(0xFFF0A9F0)),
    LanguageColor("Go", Color(0xFF375EAB)),
    LanguageColor("Golo", Color(0xFF88562A)),
    LanguageColor("Gosu", Color(0xFF82937F)),
    LanguageColor("Grammatical Framework", Color(0xFF79AA7A)),
    LanguageColor("Groovy", Color(0xFFE69F56)),
    LanguageColor("Handlebars", Color(0xFF01A9D6)),
    LanguageColor("Harbour", Color(0xFF0E60E3)),
    LanguageColor("Haskell", Color(0xFF29B544)),
    LanguageColor("Haxe", Color(0xFFDF7900)),
    LanguageColor("HTML", Color(0xFFE44B23)),
    LanguageColor("Hy", Color(0xFF7790B2)),
    LanguageColor("IDL", Color(0xFFA3522F)),
    LanguageColor("Io", Color(0xFFA9188D)),
    LanguageColor("Ioke", Color(0xFF078193)),
    LanguageColor("Isabelle", Color(0xFFFEFE00)),
    LanguageColor("J", Color(0xFF9EEDFF)),
    LanguageColor("Java", Color(0xFFB07219)),
    LanguageColor("JavaScript", Color(0xFFF1E05A)),
    LanguageColor("JFlex", Color(0xFFDBCA00)),
    LanguageColor("JSONiq", Color(0xFF40D47E)),
    LanguageColor("Julia", Color(0xFFA270BA)),
    LanguageColor("Jupyter Notebook", Color(0xFFDA5B0B)),
    LanguageColor("Kotlin", Color(0xFFF18E33)),
    LanguageColor("KRL", Color(0xFF28431F)),
    LanguageColor("Lasso", Color(0xFF999999)),
    LanguageColor("Latte", Color(0xFFA8FF97)),
    LanguageColor("Lex", Color(0xFFDBCA00)),
    LanguageColor("LFE", Color(0xFF004200)),
    LanguageColor("LiveScript", Color(0xFF499886)),
    LanguageColor("LOLCODE", Color(0xFFCC9900)),
    LanguageColor("LookML", Color(0xFF652B81)),
    LanguageColor("LSL", Color(0xFF3D9970)),
    LanguageColor("Lua", Color(0xFF000080)),
    LanguageColor("Makefile", Color(0xFF427819)),
    LanguageColor("Mask", Color(0xFFF97732)),
    LanguageColor("Matlab", Color(0xFFBB92AC)),
    LanguageColor("Max", Color(0xFFC4A79C)),
    LanguageColor("MAXScript", Color(0xFF00A6A6)),
    LanguageColor("Mercury", Color(0xFFFF2B2B)),
    LanguageColor("Metal", Color(0xFF8F14E9)),
    LanguageColor("Mirah", Color(0xFFC7A938)),
    LanguageColor("MTML", Color(0xFFB7E1F4)),
    LanguageColor("NCL", Color(0xFF28431F)),
    LanguageColor("Nemerle", Color(0xFF3D3C6E)),
    LanguageColor("nesC", Color(0xFF94B0C7)),
    LanguageColor("NetLinx", Color(0xFF0AA0FF)),
    LanguageColor("NetLinx+ERB", Color(0xFF747FAA)),
    LanguageColor("NetLogo", Color(0xFFFF6375)),
    LanguageColor("NewLisp", Color(0xFF87AED7)),
    LanguageColor("Nimrod", Color(0xFF37775B)),
    LanguageColor("Nit", Color(0xFF009917)),
    LanguageColor("Nix", Color(0xFF7E7EFF)),
    LanguageColor("Nu", Color(0xFFC9DF40)),
    LanguageColor("Objective-C", Color(0xFF438EFF)),
    LanguageColor("Objective-C++", Color(0xFF6866FB)),
    LanguageColor("Objective-J", Color(0xFFFF0C5A)),
    LanguageColor("OCaml", Color(0xFF3BE133)),
    LanguageColor("Omgrofl", Color(0xFFCABBFF)),
    LanguageColor("ooc", Color(0xFFB0B77E)),
    LanguageColor("Opal", Color(0xFFF7EDE0)),
    LanguageColor("Oxygene", Color(0xFFCDD0E3)),
    LanguageColor("Oz", Color(0xFFFAB738)),
    LanguageColor("Pan", Color(0xFFCC0000)),
    LanguageColor("Papyrus", Color(0xFF6600CC)),
    LanguageColor("Parrot", Color(0xFFF3CA0A)),
    LanguageColor("Pascal", Color(0xFFB0CE4E)),
    LanguageColor("PAWN", Color(0xFFDBB284)),
    LanguageColor("Perl", Color(0xFF0298C3)),
    LanguageColor("Perl6", Color(0xFF0000FB)),
    LanguageColor("PHP", Color(0xFF4F5D95)),
    LanguageColor("PigLatin", Color(0xFFFCD7DE)),
    LanguageColor("Pike", Color(0xFF005390)),
    LanguageColor("PLSQL", Color(0xFFDAD8D8)),
    LanguageColor("PogoScript", Color(0xFFD80074)),
    LanguageColor("Processing", Color(0xFF0096D8)),
    LanguageColor("Prolog", Color(0xFF74283C)),
    LanguageColor("Propeller Spin", Color(0xFF7FA2A7)),
    LanguageColor("Puppet", Color(0xFF302B6D)),
    LanguageColor("Pure Data", Color(0xFF91DE79)),
    LanguageColor("PureBasic", Color(0xFF5A6986)),
    LanguageColor("PureScript", Color(0xFF1D222D)),
    LanguageColor("Python", Color(0xFF3572A5)),
    LanguageColor("QML", Color(0xFF44A51C)),
    LanguageColor("R", Color(0xFF198CE7)),
    LanguageColor("Racket", Color(0xFF22228F)),
    LanguageColor("Ragel in Ruby Host", Color(0xFF9D5200)),
    LanguageColor("RAML", Color(0xFF77D9FB)),
    LanguageColor("Rebol", Color(0xFF358A5B)),
    LanguageColor("Red", Color(0xFFEE0000)),
    LanguageColor("Ren'Py", Color(0xFFFF7F7F)),
    LanguageColor("Rouge", Color(0xFFCC0088)),
    LanguageColor("Ruby", Color(0xFF701516)),
    LanguageColor("Rust", Color(0xFFDEA584)),
    LanguageColor("SaltStack", Color(0xFF646464)),
    LanguageColor("SAS", Color(0xFFB34936)),
    LanguageColor("Scala", Color(0xFFDC322F)),
    LanguageColor("Scheme", Color(0xFF1E4AEC)),
    LanguageColor("Self", Color(0xFF0579AA)),
    LanguageColor("Shell", Color(0xFF89E051)),
    LanguageColor("Shen", Color(0xFF120F14)),
    LanguageColor("Slash", Color(0xFF007EFF)),
    LanguageColor("Slim", Color(0xFFFF8F77)),
    LanguageColor("Smalltalk", Color(0xFF596706)),
    LanguageColor("SourcePawn", Color(0xFF5C7611)),
    LanguageColor("SQF", Color(0xFF3F3F3F)),
    LanguageColor("Squirrel", Color(0xFF800000)),
    LanguageColor("Stan", Color(0xFFB2011D)),
    LanguageColor("Standard ML", Color(0xFFDC566D)),
    LanguageColor("SuperCollider", Color(0xFF46390B)),
    LanguageColor("Swift", Color(0xFFFFAC45)),
    LanguageColor("SystemVerilog", Color(0xFFDAE1C2)),
    LanguageColor("Tcl", Color(0xFFE4CC98)),
    LanguageColor("TeX", Color(0xFF3D6117)),
    LanguageColor("Turing", Color(0xFF45F715)),
    LanguageColor("TypeScript", Color(0xFF2B7489)),
    LanguageColor("Unified Parallel C", Color(0xFF4E3617)),
    LanguageColor("Unity3D Asset", Color(0xFFAB69A1)),
    LanguageColor("UnrealScript", Color(0xFFA54C4D)),
    LanguageColor("Vala", Color(0xFFFBE5CD)),
    LanguageColor("Verilog", Color(0xFFB2B7F8)),
    LanguageColor("VHDL", Color(0xFFADB2CB)),
    LanguageColor("VimL", Color(0xFF199F4B)),
    LanguageColor("Visual Basic", Color(0xFF945DB7)),
    LanguageColor("Volt", Color(0xFF1F1F1F)),
    LanguageColor("Vue", Color(0xFF2C3E50)),
    LanguageColor("Web Ontology Language", Color(0xFF9CC9DD)),
    LanguageColor("wisp", Color(0xFF7582D1)),
    LanguageColor("X10", Color(0xFF4B6BEF)),
    LanguageColor("xBase", Color(0xFF403A40)),
    LanguageColor("XC", Color(0xFF99DA07)),
    LanguageColor("XQuery", Color(0xFF5232E7)),
    LanguageColor("Zephir", Color(0xFF118F9E))
)